title: Cansu's Math Notes
#logo: /assets/img/logo.png
description: Hellow world! I am a mathematics and statistics graduate student at Georgetown Unversity. This site features my grad school notes.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
